trigger:
  paths:
    include:
      - terraform/**
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      name: 'Default'

    steps:

    # 1️⃣ Download SSH Public Key from Secure Files
    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'id_rsa_azure.pub'
      displayName: 'Download SSH Public Key'

    # 2️⃣ Copy SSH key into Terraform module folder
    - script: |
        echo "Copying SSH public key into Terraform module"
        mkdir -p ~/.ssh
        cp $(download_ssh_key.secureFilePath) ~/.ssh/id_rsa_azure.pub
        cp $(download_ssh_key.secureFilePath) azure/modules/compute/id_rsa_azure.pub
        echo "Listing contents of azure/modules/compute/"
        ls -al azure/modules/compute/
      displayName: 'Prepare SSH Public Key for Terraform'

    # 3️⃣ Download Terraform variable file (dev.tfvars) securely
    - task: DownloadSecureFile@1
      name: download_tfvars
      inputs:
        secureFile: 'dev.tfvars'
      displayName: 'Download Terraform Variable File'

    # 4️⃣ Terraform Init, Plan, and Apply
    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan, and Apply'
      inputs:
        azureSubscription: 'azure-devops-connection'  # Your service connection
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform/azure
        inlineScript: |
          # Copy the Secure File to working directory as dev.tfvars
          echo "Copying tfvars file to working directory..."
          cp $(download_tfvars.secureFilePath) ./dev.tfvars

          # Initialize Terraform
          echo "Initializing Terraform..."
          terraform init -input=false

          # Terraform plan
          echo "Planning Terraform changes..."
          terraform plan -input=false -var-file=dev.tfvars

          # Terraform apply
          echo "Applying Terraform..."
          terraform apply -input=false -auto-approve -var-file=dev.tfvars
