trigger:
  paths:
    include:
      - terraform/**
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      name: 'Default'

    steps:

    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'id_rsa_azure.pub'

    - script: |
        echo "Copying SSH public key into Terraform module"
        mkdir -p ~/.ssh
        cp $(download_ssh_key.secureFilePath) ~/.ssh/id_rsa_azure.pub
        cp $(download_ssh_key.secureFilePath) terraform/modules/compute/id_rsa_azure.pub
        echo "Listing contents of terraform/modules/compute/"
        ls -al terraform/modules/compute/
      displayName: 'Extract SSH Public Key for Terraform'

    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan and Apply'
      inputs:
        azureSubscription: 'azure-devops-connection'
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform/azure
        inlineScript: |
          echo "Initializing Terraform..."
          terraform init -input=false 

          echo "Planning Terraform changes..."
          terraform plan -input=false \
            -var "application_name=$(application_name)" \
            -var "environment=$(environment)" \
            -var "location=$(location)" \
            -var "admin_username=$(admin_username)" \
            -var "admin_password=$(admin_password)" \
            -var "mysql_admin_username=$(mysql_admin_username)" \
            -var "mysql_admin_password=$(mysql_admin_password)" \
            -var "mysql_database_name=$(mysql_database_name)" \
            -var 'vnet_address_space=$(vnet_address_space)' \
            -var 'public_subnet_address_prefixes=$(public_subnet_address_prefixes)' \
            -var 'private_subnet_address_prefixes=$(private_subnet_address_prefixes)' \
            -var "vm_size=$(vm_size)" \
            -var "ssh_public_key=$(ssh_public_key)"

          echo "Applying Terraform..."
          terraform apply -input=false -auto-approve \
            -var "application_name=$(application_name)" \
            -var "environment=$(environment)" \
            -var "location=$(location)" \
            -var "admin_username=$(admin_username)" \
            -var "admin_password=$(admin_password)" \
            -var "mysql_admin_username=$(mysql_admin_username)" \
            -var "mysql_admin_password=$(mysql_admin_password)" \
            -var "mysql_database_name=$(mysql_database_name)" \
            -var 'vnet_address_space=$(vnet_address_space)' \
            -var 'public_subnet_address_prefixes=$(public_subnet_address_prefixes)' \
            -var 'private_subnet_address_prefixes=$(private_subnet_address_prefixes)' \
            -var "vm_size=$(vm_size)" \
            -var "ssh_public_key=$(ssh_public_key)"
